theme: jekyll-theme-hacker
title: hardweird inc.
description: Games and hacking for fun and profit.

permalink: /:categories/:year/:y_day/:title/

github: [metadata]

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
